### ISSUE TITLE
Initial Model Implementation & Reproduction

### ISSUE THREAD

**Issue by weihua916** [pyg-team/pytorch-frame#27]
We aim to include four popular models in the initial release. This issue keeps track of our progress.

[FT-Transformer](https://arxiv.org/pdf/2106.11959.pdf) @kaidic @weihua916 
- [x] Initial implementation https://github.com/pyg-team/pytorch-frame/pull/12
- [x] Initial implementation of `LinearBucketEncoder`  and `LinearPeriodicEncoder`. https://github.com/pyg-team/pytorch-frame/pull/30 https://github.com/pyg-team/pytorch-frame/pull/31 
- [x] Include at least 2 datasets from the paper https://github.com/pyg-team/pytorch-frame/pull/37
- [x] Reproducibility of FT-Transformer
- [x] Reproducibility of ResNet.
- [x] Reproducibility of `LinearBucketEncoder` ad `LinearPeriodicEncoder`.

[Trompt](https://arxiv.org/pdf/2305.18446.pdf) @weihua916 
- [x] Initial implementation https://github.com/pyg-team/pytorch-frame/pull/25
- [x] Include at least 2 datasets from the paper https://github.com/pyg-team/pytorch-frame/pull/33
- [x] Reproducibility https://github.com/pyg-team/pytorch-frame/pull/39

[TabNet](https://arxiv.org/pdf/1908.07442.pdf) @zechengz @weihua916 
- [x] Initial implementation
- [x] Include at least 2 datasets from the paper
- [x] Reproducibility

[ExcelFormer](https://arxiv.org/abs/2301.02819) @yiweny 
- [x] Initial implementation
- [x] Include at least 2 datasets from the paper
- [x] Reproducibility

[TabTransformer](https://arxiv.org/abs/2012.06678) @yiweny 
- [x] Initial implementation
- [x] Include at least 2 datasets from the paper
- [x] Reproducibility

Example encoding + self-attention + sum pooling @weihua916 
- [x] example code. https://github.com/pyg-team/pytorch-frame/pull/54
